"""update_forma_pago_to_id

Revision ID: 0866c578c0ba
Revises: 7ca243025e9b
Create Date: 2026-03-09 14:40:16.272717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0866c578c0ba'
down_revision: Union[str, Sequence[str], None] = '7ca243025e9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotizaciones',
    sa.Column('id_cotizacion', sa.Integer(), nullable=False),
    sa.Column('numero_cotizacion', sa.Integer(), nullable=True),
    sa.Column('id_almacen', sa.Integer(), nullable=False),
    sa.Column('fecha_emision', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_empleado', sa.Integer(), nullable=True),
    sa.Column('id_moneda', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('garantia_meses', sa.Integer(), nullable=True),
    sa.Column('id_forma_pago', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cartera_clientes.id_cliente'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_empleado'], ['empleados.id_empleado'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_cotizacion')
    )
    op.create_index(op.f('ix_cotizaciones_id_cotizacion'), 'cotizaciones', ['id_cotizacion'], unique=False)
    op.create_index(op.f('ix_cotizaciones_numero_cotizacion'), 'cotizaciones', ['numero_cotizacion'], unique=False)
    op.create_table('cotizaciones_detalles',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_cotizacion', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('precio_producto', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('regalo', sa.Boolean(), nullable=True),
    sa.Column('id_moneda', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cotizacion'], ['cotizaciones.id_cotizacion'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_index(op.f('ix_cotizaciones_detalles_id_detalle'), 'cotizaciones_detalles', ['id_detalle'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cotizaciones_detalles_id_detalle'), table_name='cotizaciones_detalles')
    op.drop_table('cotizaciones_detalles')
    op.drop_index(op.f('ix_cotizaciones_numero_cotizacion'), table_name='cotizaciones')
    op.drop_index(op.f('ix_cotizaciones_id_cotizacion'), table_name='cotizaciones')
    op.drop_table('cotizaciones')
    # ### end Alembic commands ###
