"""add_is_admin_to_empleado

Revision ID: 12c5d96585bd
Revises: 433537da8aab
Create Date: 2026-02-24 15:50:42.859885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12c5d96585bd'
down_revision: Union[str, Sequence[str], None] = '433537da8aab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empleados', 'is_admin')
    # ### end Alembic commands ###
