"""refactor_kpi_to_master_detail

Revision ID: 24b33a54556a
Revises: f0d47fefc41a
Create Date: 2026-03-02 13:06:02.174613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24b33a54556a'
down_revision: Union[str, Sequence[str], None] = 'f0d47fefc41a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalle_informe_kpi',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_informe', sa.Integer(), nullable=True),
    sa.Column('id_meta', sa.Integer(), nullable=True),
    sa.Column('valor_meta', sa.Integer(), nullable=False),
    sa.Column('puntos_por_unidad', sa.Integer(), nullable=False),
    sa.Column('valor_real', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_informe'], ['informe_productividad_semanal.id_informe'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_meta'], ['configuracion_metas_globales.id_meta'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    op.create_index(op.f('ix_detalle_informe_kpi_id_detalle'), 'detalle_informe_kpi', ['id_detalle'], unique=False)
    op.drop_column('informe_productividad_semanal', 'real_emails')
    op.drop_column('informe_productividad_semanal', 'meta_visitas_asistidas')
    op.drop_column('informe_productividad_semanal', 'meta_visitas')
    op.drop_column('informe_productividad_semanal', 'meta_cotizaciones')
    op.drop_column('informe_productividad_semanal', 'real_visitas')
    op.drop_column('informe_productividad_semanal', 'meta_emails')
    op.drop_column('informe_productividad_semanal', 'meta_llamadas')
    op.drop_column('informe_productividad_semanal', 'real_visitas_asistidas')
    op.drop_column('informe_productividad_semanal', 'real_llamadas')
    op.drop_column('informe_productividad_semanal', 'real_cotizaciones')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('informe_productividad_semanal', sa.Column('real_cotizaciones', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('informe_productividad_semanal', sa.Column('real_llamadas', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('informe_productividad_semanal', sa.Column('real_visitas_asistidas', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('informe_productividad_semanal', sa.Column('meta_llamadas', sa.INTEGER(), server_default=sa.text('30'), autoincrement=False, nullable=True))
    op.add_column('informe_productividad_semanal', sa.Column('meta_emails', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=True))
    op.add_column('informe_productividad_semanal', sa.Column('real_visitas', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('informe_productividad_semanal', sa.Column('meta_cotizaciones', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('informe_productividad_semanal', sa.Column('meta_visitas', sa.INTEGER(), server_default=sa.text('25'), autoincrement=False, nullable=True))
    op.add_column('informe_productividad_semanal', sa.Column('meta_visitas_asistidas', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('informe_productividad_semanal', sa.Column('real_emails', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_detalle_informe_kpi_id_detalle'), table_name='detalle_informe_kpi')
    op.drop_table('detalle_informe_kpi')
    # ### end Alembic commands ###
