"""add_estado_to_detalle_plan

Revision ID: 2e90773c75dc
Revises: aea1fecc9502
Create Date: 2026-03-03 18:38:16.036182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e90773c75dc'
down_revision: Union[str, Sequence[str], None] = 'aea1fecc9502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('detalle_plan_trabajo', sa.Column('estado', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('detalle_plan_trabajo', 'estado')
    # ### end Alembic commands ###
