"""revert_kpi_to_static_columns

Revision ID: 377947d24d14
Revises: 24b33a54556a
Create Date: 2026-03-02 13:39:17.923168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377947d24d14'
down_revision: Union[str, Sequence[str], None] = '24b33a54556a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_informe_kpi_id_detalle'), table_name='detalle_informe_kpi')
    op.drop_table('detalle_informe_kpi')
    op.add_column('informe_productividad_semanal', sa.Column('meta_visitas', sa.Integer(), nullable=True))
    op.add_column('informe_productividad_semanal', sa.Column('real_visitas', sa.Integer(), nullable=True))
    op.add_column('informe_productividad_semanal', sa.Column('meta_visitas_asistidas', sa.Integer(), nullable=True))
    op.add_column('informe_productividad_semanal', sa.Column('real_visitas_asistidas', sa.Integer(), nullable=True))
    op.add_column('informe_productividad_semanal', sa.Column('meta_llamadas', sa.Integer(), nullable=True))
    op.add_column('informe_productividad_semanal', sa.Column('real_llamadas', sa.Integer(), nullable=True))
    op.add_column('informe_productividad_semanal', sa.Column('meta_emails', sa.Integer(), nullable=True))
    op.add_column('informe_productividad_semanal', sa.Column('real_emails', sa.Integer(), nullable=True))
    op.add_column('informe_productividad_semanal', sa.Column('meta_cotizaciones', sa.Integer(), nullable=True))
    op.add_column('informe_productividad_semanal', sa.Column('real_cotizaciones', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('informe_productividad_semanal', 'real_cotizaciones')
    op.drop_column('informe_productividad_semanal', 'meta_cotizaciones')
    op.drop_column('informe_productividad_semanal', 'real_emails')
    op.drop_column('informe_productividad_semanal', 'meta_emails')
    op.drop_column('informe_productividad_semanal', 'real_llamadas')
    op.drop_column('informe_productividad_semanal', 'meta_llamadas')
    op.drop_column('informe_productividad_semanal', 'real_visitas_asistidas')
    op.drop_column('informe_productividad_semanal', 'meta_visitas_asistidas')
    op.drop_column('informe_productividad_semanal', 'real_visitas')
    op.drop_column('informe_productividad_semanal', 'meta_visitas')
    op.create_table('detalle_informe_kpi',
    sa.Column('id_detalle', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_informe', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_meta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valor_meta', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('puntos_por_unidad', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('valor_real', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_informe'], ['informe_productividad_semanal.id_informe'], name=op.f('detalle_informe_kpi_id_informe_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_meta'], ['configuracion_metas_globales.id_meta'], name=op.f('detalle_informe_kpi_id_meta_fkey')),
    sa.PrimaryKeyConstraint('id_detalle', name=op.f('detalle_informe_kpi_pkey'))
    )
    op.create_index(op.f('ix_detalle_informe_kpi_id_detalle'), 'detalle_informe_kpi', ['id_detalle'], unique=False)
    # ### end Alembic commands ###
