"""sincronizacion_inicial_corregida

Revision ID: 3824faf7efc2
Revises: 
Create Date: 2026-02-24 10:40:20.307803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3824faf7efc2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cartera_clientes_ruc_dni_key'), 'cartera_clientes', type_='unique')
    op.create_index(op.f('ix_cartera_clientes_id_cliente'), 'cartera_clientes', ['id_cliente'], unique=False)
    op.create_index(op.f('ix_cartera_clientes_ruc_dni'), 'cartera_clientes', ['ruc_dni'], unique=True)
    op.alter_column('departamentos', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('departamentos', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_departamentos_id_departamento'), 'departamentos', ['id_departamento'], unique=False)
    op.drop_constraint(op.f('detalle_plan_trabajo_id_plan_dia_semana_hora_programada_key'), 'detalle_plan_trabajo', type_='unique')
    op.create_index(op.f('ix_detalle_plan_trabajo_id_detalle'), 'detalle_plan_trabajo', ['id_detalle'], unique=False)
    op.alter_column('distritos', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('distritos', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_distritos_id_distrito'), 'distritos', ['id_distrito'], unique=False)
    op.drop_constraint(op.f('empleados_dni_key'), 'empleados', type_='unique')
    op.create_index(op.f('ix_empleados_id_empleado'), 'empleados', ['id_empleado'], unique=False)
    op.alter_column('incentivos_pagos', 'fecha_generacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_incentivos_pagos_id_incentivo'), 'incentivos_pagos', ['id_incentivo'], unique=False)
    op.create_index(op.f('ix_informe_productividad_semanal_id_informe'), 'informe_productividad_semanal', ['id_informe'], unique=False)
    op.alter_column('maestro_entidades', 'fecha_registro',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('maestro_entidades_ruc_key'), 'maestro_entidades', type_='unique')
    op.create_index(op.f('ix_maestro_entidades_id_entidad'), 'maestro_entidades', ['id_entidad'], unique=False)
    op.create_index(op.f('ix_maestro_entidades_ruc'), 'maestro_entidades', ['ruc'], unique=True)
    op.alter_column('plan_trabajo_semanal', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('plan_trabajo_semanal_id_empleado_fecha_inicio_semana_key'), 'plan_trabajo_semanal', type_='unique')
    op.create_index(op.f('ix_plan_trabajo_semanal_id_plan'), 'plan_trabajo_semanal', ['id_plan'], unique=False)
    op.drop_column('plan_trabajo_semanal', 'total_visitas_programadas')
    op.drop_column('plan_trabajo_semanal', 'total_emails_enviados')
    op.drop_column('plan_trabajo_semanal', 'total_llamadas_realizadas')
    op.create_index(op.f('ix_planilla_gastos_movilidad_id_gasto'), 'planilla_gastos_movilidad', ['id_gasto'], unique=False)
    op.alter_column('provincias', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('provincias', 'fecha_creacion',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_provincias_id_provincia'), 'provincias', ['id_provincia'], unique=False)
    op.alter_column('registro_auditoria_emails', 'fecha_hora',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_registro_auditoria_emails_id_email'), 'registro_auditoria_emails', ['id_email'], unique=False)
    op.alter_column('registro_auditoria_llamadas', 'fecha_hora',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_registro_auditoria_llamadas_id_llamada'), 'registro_auditoria_llamadas', ['id_llamada'], unique=False)
    op.add_column('registro_visitas', sa.Column('nombre_tecnico', sa.String(length=150), nullable=True))
    op.alter_column('registro_visitas', 'fecha_hora_checkin',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.create_index(op.f('ix_registro_visitas_id_visita'), 'registro_visitas', ['id_visita'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registro_visitas_id_visita'), table_name='registro_visitas')
    op.alter_column('registro_visitas', 'fecha_hora_checkin',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('registro_visitas', 'nombre_tecnico')
    op.drop_index(op.f('ix_registro_auditoria_llamadas_id_llamada'), table_name='registro_auditoria_llamadas')
    op.alter_column('registro_auditoria_llamadas', 'fecha_hora',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_registro_auditoria_emails_id_email'), table_name='registro_auditoria_emails')
    op.alter_column('registro_auditoria_emails', 'fecha_hora',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_provincias_id_provincia'), table_name='provincias')
    op.alter_column('provincias', 'fecha_creacion',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('provincias', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_planilla_gastos_movilidad_id_gasto'), table_name='planilla_gastos_movilidad')
    op.add_column('plan_trabajo_semanal', sa.Column('total_llamadas_realizadas', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('plan_trabajo_semanal', sa.Column('total_emails_enviados', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('plan_trabajo_semanal', sa.Column('total_visitas_programadas', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_plan_trabajo_semanal_id_plan'), table_name='plan_trabajo_semanal')
    op.create_unique_constraint(op.f('plan_trabajo_semanal_id_empleado_fecha_inicio_semana_key'), 'plan_trabajo_semanal', ['id_empleado', 'fecha_inicio_semana'], postgresql_nulls_not_distinct=False)
    op.alter_column('plan_trabajo_semanal', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_maestro_entidades_ruc'), table_name='maestro_entidades')
    op.drop_index(op.f('ix_maestro_entidades_id_entidad'), table_name='maestro_entidades')
    op.create_unique_constraint(op.f('maestro_entidades_ruc_key'), 'maestro_entidades', ['ruc'], postgresql_nulls_not_distinct=False)
    op.alter_column('maestro_entidades', 'fecha_registro',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_informe_productividad_semanal_id_informe'), table_name='informe_productividad_semanal')
    op.drop_index(op.f('ix_incentivos_pagos_id_incentivo'), table_name='incentivos_pagos')
    op.alter_column('incentivos_pagos', 'fecha_generacion',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index(op.f('ix_empleados_id_empleado'), table_name='empleados')
    op.create_unique_constraint(op.f('empleados_dni_key'), 'empleados', ['dni'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_distritos_id_distrito'), table_name='distritos')
    op.alter_column('distritos', 'fecha_creacion',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('distritos', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_detalle_plan_trabajo_id_detalle'), table_name='detalle_plan_trabajo')
    op.create_unique_constraint(op.f('detalle_plan_trabajo_id_plan_dia_semana_hora_programada_key'), 'detalle_plan_trabajo', ['id_plan', 'dia_semana', 'hora_programada'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_departamentos_id_departamento'), table_name='departamentos')
    op.alter_column('departamentos', 'fecha_creacion',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('departamentos', 'activo',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_cartera_clientes_ruc_dni'), table_name='cartera_clientes')
    op.drop_index(op.f('ix_cartera_clientes_id_cliente'), table_name='cartera_clientes')
    op.create_unique_constraint(op.f('cartera_clientes_ruc_dni_key'), 'cartera_clientes', ['ruc_dni'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
