"""add_sales_metrics_to_kpi

Revision ID: 40e89e412241
Revises: 842d4b3ba222
Create Date: 2026-03-02 14:52:25.248399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40e89e412241'
down_revision: Union[str, Sequence[str], None] = '842d4b3ba222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('informe_productividad_semanal', sa.Column('real_ventas_monto', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('maestro_metas', sa.Column('meta_ventas', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('maestro_metas', sa.Column('puntos_venta', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maestro_metas', 'puntos_venta')
    op.drop_column('maestro_metas', 'meta_ventas')
    op.drop_column('informe_productividad_semanal', 'real_ventas_monto')
    # ### end Alembic commands ###
