"""add_auth_fields_to_empleado

Revision ID: 433537da8aab
Revises: d46cbcf73d28
Create Date: 2026-02-24 15:43:29.473697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '433537da8aab'
down_revision: Union[str, Sequence[str], None] = 'd46cbcf73d28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('usuario', sa.String(length=50), nullable=True))
    op.add_column('empleados', sa.Column('hashed_password', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_empleados_usuario'), 'empleados', ['usuario'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_empleados_usuario'), table_name='empleados')
    op.drop_column('empleados', 'hashed_password')
    op.drop_column('empleados', 'usuario')
    # ### end Alembic commands ###
