"""add_fecha_inicio_fin_to_maestro_metas

Revision ID: 4e92ef4fe41d
Revises: 2e90773c75dc
Create Date: 2026-03-04 09:32:30.409670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e92ef4fe41d'
down_revision: Union[str, Sequence[str], None] = '2e90773c75dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maestro_metas', sa.Column('fecha_inicio_semana', sa.Date(), nullable=True))
    op.add_column('maestro_metas', sa.Column('fecha_fin_semana', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maestro_metas', 'fecha_fin_semana')
    op.drop_column('maestro_metas', 'fecha_inicio_semana')
    # ### end Alembic commands ###
