"""add_hora_registro_to_gasto

Revision ID: 6106cef0a127
Revises: 4e92ef4fe41d
Create Date: 2026-03-04 10:57:28.668810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6106cef0a127'
down_revision: Union[str, Sequence[str], None] = '4e92ef4fe41d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planilla_gastos_movilidad', sa.Column('hora_registro', sa.Time(), server_default=sa.text('CURRENT_TIME'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('planilla_gastos_movilidad', 'hora_registro')
    # ### end Alembic commands ###
