"""remove_is_active_from_maestro_metas

Revision ID: 66fa52eb1945
Revises: 40e89e412241
Create Date: 2026-03-03 10:14:43.059518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66fa52eb1945'
down_revision: Union[str, Sequence[str], None] = '40e89e412241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maestro_metas', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maestro_metas', sa.Column('is_active', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
