"""use_enum_for_plan_status

Revision ID: 73d5a559f462
Revises: f0e30b4e21e1
Create Date: 2026-02-26 10:11:59.047655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73d5a559f462'
down_revision: Union[str, Sequence[str], None] = 'f0e30b4e21e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Crear el tipo ENUM en Postgres
    estado_plan_enum = sa.Enum('Borrador', 'Enviado', 'Aprobado', 'Rechazado', name='estado_plan_enum')
    estado_plan_enum.create(op.get_bind())

    # 2. Eliminar el DEFAULT actual de VARCHAR antes de cambiar de tipo
    op.execute("ALTER TABLE plan_trabajo_semanal ALTER COLUMN estado DROP DEFAULT")

    # 3. Alterar la columna con casting explícito
    op.execute("ALTER TABLE plan_trabajo_semanal ALTER COLUMN estado TYPE estado_plan_enum USING estado::estado_plan_enum")
    
    # 4. Volver a poner el default
    op.execute("ALTER TABLE plan_trabajo_semanal ALTER COLUMN estado SET DEFAULT 'Borrador'")



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plan_trabajo_semanal', 'estado',
               existing_type=sa.Enum('Borrador', 'Enviado', 'Aprobado', 'Rechazado', name='estado_plan_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'Borrador'::character varying"))
    # ### end Alembic commands ###
