"""create_cotizacion_and_detalle_tables

Revision ID: 7ca243025e9b
Revises: 6106cef0a127
Create Date: 2026-03-09 12:02:07.600453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ca243025e9b'
down_revision: Union[str, Sequence[str], None] = '6106cef0a127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
