"""implement_maestro_metas_centralized

Revision ID: 842d4b3ba222
Revises: 377947d24d14
Create Date: 2026-03-02 13:46:46.998438

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '842d4b3ba222'
down_revision: Union[str, Sequence[str], None] = '377947d24d14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maestro_metas',
    sa.Column('id_maestro', sa.Integer(), nullable=False),
    sa.Column('nombre_meta', sa.String(length=100), nullable=False),
    sa.Column('meta_visitas', sa.Integer(), nullable=True),
    sa.Column('meta_visitas_asistidas', sa.Integer(), nullable=True),
    sa.Column('meta_llamadas', sa.Integer(), nullable=True),
    sa.Column('meta_emails', sa.Integer(), nullable=True),
    sa.Column('meta_cotizaciones', sa.Integer(), nullable=True),
    sa.Column('puntos_visita', sa.Integer(), nullable=True),
    sa.Column('puntos_visita_asistida', sa.Integer(), nullable=True),
    sa.Column('puntos_llamada', sa.Integer(), nullable=True),
    sa.Column('puntos_email', sa.Integer(), nullable=True),
    sa.Column('puntos_cotizacion', sa.Integer(), nullable=True),
    sa.Column('puntaje_objetivo', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=True),
    sa.PrimaryKeyConstraint('id_maestro')
    )
    op.create_index(op.f('ix_maestro_metas_id_maestro'), 'maestro_metas', ['id_maestro'], unique=False)
    op.drop_index(op.f('ix_configuracion_metas_globales_id_meta'), table_name='configuracion_metas_globales')
    op.drop_table('configuracion_metas_globales')
    op.add_column('informe_productividad_semanal', sa.Column('id_maestro_meta', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'informe_productividad_semanal', 'maestro_metas', ['id_maestro_meta'], ['id_maestro'])
    op.drop_column('informe_productividad_semanal', 'meta_emails')
    op.drop_column('informe_productividad_semanal', 'meta_llamadas')
    op.drop_column('informe_productividad_semanal', 'porcentaje_alcance')
    op.drop_column('informe_productividad_semanal', 'puntaje_objetivo')
    op.drop_column('informe_productividad_semanal', 'meta_visitas')
    op.drop_column('informe_productividad_semanal', 'meta_visitas_asistidas')
    op.drop_column('informe_productividad_semanal', 'meta_cotizaciones')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('informe_productividad_semanal', sa.Column('meta_cotizaciones', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('informe_productividad_semanal', sa.Column('meta_visitas_asistidas', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('informe_productividad_semanal', sa.Column('meta_visitas', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('informe_productividad_semanal', sa.Column('porcentaje_alcance', sa.NUMERIC(precision=5, scale=2), sa.Computed('(((puntos_alcanzados)::numeric / (NULLIF(puntaje_objetivo, 0))::numeric) * (100)::numeric)', persisted=True), autoincrement=False, nullable=True))
    op.add_column('informe_productividad_semanal', sa.Column('puntaje_objetivo', sa.INTEGER(), server_default=sa.text('205'), autoincrement=False, nullable=True))
    op.add_column('informe_productividad_semanal', sa.Column('meta_llamadas', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('informe_productividad_semanal', sa.Column('meta_emails', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'informe_productividad_semanal', type_='foreignkey')
    op.drop_column('informe_productividad_semanal', 'id_maestro_meta')
    op.create_table('configuracion_metas_globales',
    sa.Column('id_meta', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('clave', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('valor', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('puntos_por_unidad', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('descripcion', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('editable_por_supervisor', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_meta', name=op.f('configuracion_metas_globales_pkey')),
    sa.UniqueConstraint('clave', name=op.f('configuracion_metas_globales_clave_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_configuracion_metas_globales_id_meta'), 'configuracion_metas_globales', ['id_meta'], unique=False)
    op.drop_index(op.f('ix_maestro_metas_id_maestro'), table_name='maestro_metas')
    op.drop_table('maestro_metas')
    # ### end Alembic commands ###
