"""add_id_empleado_to_cartera

Revision ID: 8a577f6b3a40
Revises: 9fb44eb61d6c
Create Date: 2026-02-25 11:00:49.198278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a577f6b3a40'
down_revision: Union[str, Sequence[str], None] = '9fb44eb61d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cartera_clientes', sa.Column('id_empleado', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cartera_clientes', 'empleados', ['id_empleado'], ['id_empleado'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cartera_clientes', type_='foreignkey')
    op.drop_column('cartera_clientes', 'id_empleado')
    # ### end Alembic commands ###
