"""use_email_for_login

Revision ID: 9fb44eb61d6c
Revises: 12c5d96585bd
Create Date: 2026-02-24 16:01:13.373683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fb44eb61d6c'
down_revision: Union[str, Sequence[str], None] = '12c5d96585bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('empleados', 'email_corporativo',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_index(op.f('ix_empleados_usuario'), table_name='empleados')
    op.create_index(op.f('ix_empleados_email_corporativo'), 'empleados', ['email_corporativo'], unique=True)
    op.drop_column('empleados', 'usuario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_empleados_email_corporativo'), table_name='empleados')
    op.create_index(op.f('ix_empleados_usuario'), 'empleados', ['usuario'], unique=True)
    op.alter_column('empleados', 'email_corporativo',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
