"""add_url_foto_prueba_to_crm

Revision ID: d46cbcf73d28
Revises: 3824faf7efc2
Create Date: 2026-02-24 10:43:18.802426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd46cbcf73d28'
down_revision: Union[str, Sequence[str], None] = '3824faf7efc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registro_auditoria_emails', sa.Column('url_foto_prueba', sa.Text(), nullable=True))
    op.add_column('registro_auditoria_llamadas', sa.Column('url_foto_prueba', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registro_auditoria_llamadas', 'url_foto_prueba')
    op.drop_column('registro_auditoria_emails', 'url_foto_prueba')
    # ### end Alembic commands ###
