"""add_global_metas_config

Revision ID: f0d47fefc41a
Revises: f647181d8cea
Create Date: 2026-03-02 12:50:34.313015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0d47fefc41a'
down_revision: Union[str, Sequence[str], None] = 'f647181d8cea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracion_metas_globales',
    sa.Column('id_meta', sa.Integer(), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('puntos_por_unidad', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.Column('editable_por_supervisor', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_meta'),
    sa.UniqueConstraint('clave')
    )
    op.create_index(op.f('ix_configuracion_metas_globales_id_meta'), 'configuracion_metas_globales', ['id_meta'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_configuracion_metas_globales_id_meta'), table_name='configuracion_metas_globales')
    op.drop_table('configuracion_metas_globales')
    # ### end Alembic commands ###
