"""add_id_empleado_to_maestro

Revision ID: f0e30b4e21e1
Revises: 8a577f6b3a40
Create Date: 2026-02-25 11:37:42.990323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e30b4e21e1'
down_revision: Union[str, Sequence[str], None] = '8a577f6b3a40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maestro_entidades', sa.Column('id_empleado', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'maestro_entidades', 'empleados', ['id_empleado'], ['id_empleado'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'maestro_entidades', type_='foreignkey')
    op.drop_column('maestro_entidades', 'id_empleado')
    # ### end Alembic commands ###
