"""add_id_vendedor_externo_to_empleado

Revision ID: f647181d8cea
Revises: 73d5a559f462
Create Date: 2026-02-26 12:37:54.771911

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f647181d8cea'
down_revision: Union[str, Sequence[str], None] = '73d5a559f462'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empleados', sa.Column('id_vendedor_externo', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empleados', 'id_vendedor_externo')
    # ### end Alembic commands ###
